version: '3.7'

services:
  app:
    build: .
    volumes:
      - ./:/var/www
    depends_on:
      - mariadb
    ports:
      - "8981:80"

  mariadb:
    image: mariadb:lts
    environment: 
      MARIADB_PASSWORD: laravel
      MARIADB_USER: laravel
      MARIADB_DATABASE: laravel
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 10s
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
